### ISSUE TITLE
Move LOL4k and 8k dataset to Google Drive or onedrive

### ISSUE THREAD

**Issue by allanchan339** [TaoWangzj/LLFormer#3]
With Baidu Drive, the dataset is barely able to download. 
I wonder if you can move the dataset proposed to Google drive or onedrive if possible.

**Comment by TaoWangzj** [comment]
Thanks for your interesting, we will upload our dataset to the Google Drive later.

**Comment by vecbool** [comment]
This has been already in progress, and will be done in few days.

**Comment by allanchan339** [comment]
@vecbool Thank you for having the dataset uploaded. However, it seems 8K dataset link refers to 4K dataset on google drive, wonder if u wanna have a quick fix. 

In addition, I wonder why train folder in 4K datasets have only 3 x 4GB only, while test folders have 9 x 4GB

**Comment by vecbool** [comment]
Sorry, I have updated the links.

The files are still uploading. It may take several days, please wait patiently.

**Comment by vecbool** [comment]
@allanchan339 We have updated the OneDrive links instead of Google Drive due to the limination of capacity. Hope you can download the files successfully.

**Comment by allanchan339** [comment]
Unfortunately, after moving to OneDrive for business. The download process for any data.zip.XXX cannot finish being downloaded. The download process report "failed" during downloading and the downloading speed is relatively slow .... 

I dont know if it is a bug on my sides or not. I just simply use a firebox to onedrive download page, then click a download button. Usually, OneDrive should download much faster, and the download process will not corrupt. 

Therefore, I wonder if you may also upload the datasets to huggingface instead. It can serve as cloud storage and dataset class in the same time. You can simply use `push_to_hub()` to upload dataset there. I believe this act can accelerate the adaption rate on using this dataset. 

The following website can help u.

https://huggingface.co/docs/datasets/image_dataset

**Comment by vecbool** [comment]
@allanchan339 I'm sorry to hear the problem.

The error may caused by the movement of location last night. We updated the link and uploaded anther version of UHD-8K due to the request of others. Please try the new link again, and select the version you required.

If you still have the error, we will investigate into it further. Thanks for your suggestion of hugging-face. We will try it in the near future.

**Comment by eashanadhikarla** [comment]
The dataset still doesn't download using OneDrive. It automatically gets cancelled. I tried different browsers, different platforms, and even downloaded in parts. Could you please upload it to Google drive?
