### ISSUE TITLE
Dataset Error

### ISSUE THREAD

**Issue by allanchan339** [TaoWangzj/LLFormer#4]
When I am testing the dataset class. I have noticed an image pair as follows:

![image](https://user-images.githubusercontent.com/38370649/220049680-bf58bc74-2634-48c0-932e-95ee9cb899c2.png)
![image](https://user-images.githubusercontent.com/38370649/220049726-8503afa0-8de4-4677-8125-4476dd6b7222.png)
![image](https://user-images.githubusercontent.com/38370649/220049757-090fb0e8-b363-4d97-9ff6-a4d7642be292.png)

Please check if this is a valid operation or it is duplicated.

**Comment by vecbool** [comment]
This is not an error in fact. We randomly choose different parameters such as the weight of gaussian noise to generate LQ images. The parameters for this LQ image are so slight that we cannot visually distinguish it from the HQ one.

**Comment by simpler66** [comment]
Thanks for your work and share. The paper mentioned that the LQ images are generated from HQ images by the Adobe Lightroom software. And the generation process is related to three parametes, i.e., X, Y, Z. I wonder if your added noise to the LQ images that can be download from the provided links.
