### ISSUE TITLE
can't find generate_patches_UHD-LOL.py 

### ISSUE THREAD

**Issue by bobozy1999** [TaoWangzj/LLFormer#5]
![1](https://user-images.githubusercontent.com/64068459/225332926-0e228a94-d1fd-41b7-94f6-2374cde7a0c5.png)

**Comment by vecbool** [comment]
The file has been renamed to `extract_subimages_UHD.py` and is currently located in the `scripts` folder. You can find it at [extract_subimages_UHD.py](https://github.com/TaoWangzj/LLFormer/blob/main/scripts/extract_subimages_UHD.py).
We will fix it in the `REAMDME.md` soon.

**Comment by bobozy1999** [comment]
Copy that, thanks for your reply!

**Comment by vecbool** [comment]
It's our oversight. You're welcome.
