### ISSUE TITLE
Results mismatch on LOL

### ISSUE THREAD

**Issue by wyf0912** [TaoWangzj/LLFormer#8]
Hi, thanks for sharing the code.

I can get reported results on the LOL dataset using the provided checkpoint.

However, when I train the code myself by using LOL-485, the best PSNR I can achieve is around 22.08 after 1000 epochs, which is lower than 23.64 in the paper.

<img width="583" alt="image" src="https://github.com/TaoWangzj/LLFormer/assets/26561397/a283c2c0-5d15-4968-aea7-d49089fcb234">

Besides, I find the checkpoint I obtained is much different from the one you provided on other benchmarks in highlight areas, e.g., DICM. 

Could you give some suggestions for solving the problem?

Thanks

**Comment by TaoWangzj** [comment]
Hi, thanks for paying attention to our work, we'll check this out as soon as possible.

**Comment by wyf0912** [comment]
Hi, thanks for your reply. 
Can I confirm what training set did you use? The one that includes 485 pairs or?

**Comment by TaoWangzj** [comment]
Yes, we use the LOL dataset, which includes 485 pairs for training and 15 pairs for testing.

**Comment by wyf0912** [comment]
Thanks! Looking for your reply

**Comment by wyf0912** [comment]
Any updates?

**Comment by vecbool** [comment]
Please retrain the model for a longer time. In fact, we got the best PSNR results after training for 4000 epochs.

**Comment by wyf0912** [comment]
> Please retrain the model for a longer time. In fact, we got the best PSNR results after training for 4000 epochs.

Thanks~!
